"""1_first

Revision ID: 247274eeb1db
Revises: 
Create Date: 2023-04-24 18:20:09.576500

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '247274eeb1db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('btc_usd_price',
                    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_btc_usd_price_id'), 'btc_usd_price', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_btc_usd_price_id'), table_name='btc_usd_price')
    op.drop_table('btc_usd_price')
    # ### end Alembic commands ###
