"""1_first

Revision ID: 65225cc08682
Revises: 
Create Date: 2023-04-24 21:53:13.538888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65225cc08682'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('btc_usd_price',
    sa.Column('value', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_btc_usd_price_id'), 'btc_usd_price', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('phone_work', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_btc_usd_price_id'), table_name='btc_usd_price')
    op.drop_table('btc_usd_price')
    # ### end Alembic commands ###
